config/routes.rb
Sistema::Application.routes.draw do
  devise_for :users

  resources :fornecedor_custos, :path => "custos"

  resources :fornecedors, :path => 'fornecedores'

  resources :marcas

  resources :relatorios
  resources :produtos

  root :to => 'welcome#index'

end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
  attr_accessible :nome, :telefone
  has_many :produtos
  has_many :marcas
  has_many :fornecedor_custos
end

app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  # GET /fornecedors
  # GET /fornecedors.json
  def index
    @fornecedors = Fornecedor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fornecedors }
    end
  end

  # GET /fornecedors/1
  # GET /fornecedors/1.json
  def show
    @fornecedor = Fornecedor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fornecedor }
    end
  end

  # GET /fornecedors/new
  # GET /fornecedors/new.json
  def new
    @fornecedor = Fornecedor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fornecedor }
    end
  end

  # GET /fornecedors/1/edit
  def edit
    @fornecedor = Fornecedor.find(params[:id])
  end

  # POST /fornecedors
  # POST /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(params[:fornecedor])

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully created.' }
        format.json { render json: @fornecedor, status: :created, location: @fornecedor }
      else
        format.html { render action: "new" }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fornecedors/1
  # PUT /fornecedors/1.json
  def update
    @fornecedor = Fornecedor.find(params[:id])

    respond_to do |format|
      if @fornecedor.update_attributes(params[:fornecedor])
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1
  # DELETE /fornecedors/1.json
  def destroy
    @fornecedor = Fornecedor.find(params[:id])
    @fornecedor.destroy

    respond_to do |format|
      format.html { redirect_to fornecedors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/views/fornecedors/_form.html.erb
<%= form_for(@fornecedor) do |f| %>
  <% if @fornecedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
      <% @fornecedor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fornecedors/edit.html.erb
<h1>Editing fornecedor</h1>

<%= render 'form' %>

<%= link_to 'Show', @fornecedor %> |
<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/index.html.erb
<h1>Fornecedores</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fornecedors.each do |fornecedor| %>
  <tr>
    <td><%= fornecedor.nome %></td>
    <td><%= fornecedor.telefone %></td>
    <td><%= link_to 'Exibir', fornecedor %></td>
    <td><%= link_to 'Editar', edit_fornecedor_path(fornecedor) %></td>
    <td><%= link_to 'Excluir', fornecedor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Fornecedor', new_fornecedor_path %>

app/views/fornecedors/new.html.erb
<h1>New fornecedor</h1>

<%= render 'form' %>

<%= link_to 'Back', fornecedors_path %>

app/views/fornecedors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @fornecedor.nome %>
</p>

<p>
  <b>Marcas:</b>
  <%= @fornecedor.marcas.first.nome %>
</p>

<p>
  <b>Telefone:</b>
  <%= @fornecedor.telefone %>
</p>


<%= link_to 'Edit', edit_fornecedor_path(@fornecedor) %> |
<%= link_to 'Back', fornecedors_path %>