config/routes.rb
Sistema::Application.routes.draw do
  devise_for :users

  resources :fornecedor_custos, :path => "custos"

  resources :fornecedors, :path => 'fornecedores'

  resources :marcas

  resources :relatorios
  resources :produtos

  root :to => 'welcome#index'

end

app/controllers/relatorios_controller.rb
class RelatoriosController < ApplicationController
def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/views/relatorios/index.html.erb
<%- model_class = Produto -%>
<div class="page-header">
  <h1>Relatórios</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:sku) %></th>
      <th><%= model_class.human_attribute_name(:estoque) %></th>
      <th><%= model_class.human_attribute_name(:cod_fornecedor) %></th>
      <th>Custo</th>
      <th>Total em estoque</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= link_to produto.id, produto_path(produto) %></td>
        <td><%= link_to produto.nome, produto_path(produto) %></td>
        <td><%= produto.sku %></td>
        <td><%= produto.estoque %></td>
        <td><%= produto.cod_fornecedor %></td>
        <td><%= produto.fornecedor_custos.last.preco.real %></td>
        <td><%= (produto.fornecedor_custos.last.preco * produto.estoque).real %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_produto_path(produto), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      produto_path(produto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_produto_path,
            :class => 'btn btn-primary' %>