config/routes.rb
Sistema::Application.routes.draw do
  devise_for :users

  resources :fornecedor_custos, :path => "custos"

  resources :fornecedors, :path => 'fornecedores'

  resources :marcas

  resources :relatorios
  resources :produtos

  root :to => 'welcome#index'

end

app/models/fornecedor_custo.rb
class FornecedorCusto < ActiveRecord::Base
  attr_accessible :data, :obs, :preco, :produto_id
end

app/controllers/fornecedor_custos_controller.rb
class FornecedorCustosController < ApplicationController
  # GET /fornecedor_custos
  # GET /fornecedor_custos.json
  def index
    @fornecedor_custos = FornecedorCusto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fornecedor_custos }
    end
  end

  # GET /fornecedor_custos/1
  # GET /fornecedor_custos/1.json
  def show
    @fornecedor_custo = FornecedorCusto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fornecedor_custo }
    end
  end

  # GET /fornecedor_custos/new
  # GET /fornecedor_custos/new.json
  def new
    @fornecedor_custo = FornecedorCusto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fornecedor_custo }
    end
  end

  # GET /fornecedor_custos/1/edit
  def edit
    @fornecedor_custo = FornecedorCusto.find(params[:id])
  end

  # POST /fornecedor_custos
  # POST /fornecedor_custos.json
  def create
    @fornecedor_custo = FornecedorCusto.new(params[:fornecedor_custo])

    respond_to do |format|
      if @fornecedor_custo.save
        format.html { redirect_to @fornecedor_custo, notice: 'Fornecedor custo was successfully created.' }
        format.json { render json: @fornecedor_custo, status: :created, location: @fornecedor_custo }
      else
        format.html { render action: "new" }
        format.json { render json: @fornecedor_custo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fornecedor_custos/1
  # PUT /fornecedor_custos/1.json
  def update
    @fornecedor_custo = FornecedorCusto.find(params[:id])

    respond_to do |format|
      if @fornecedor_custo.update_attributes(params[:fornecedor_custo])
        format.html { redirect_to @fornecedor_custo, notice: 'Fornecedor custo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fornecedor_custo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedor_custos/1
  # DELETE /fornecedor_custos/1.json
  def destroy
    @fornecedor_custo = FornecedorCusto.find(params[:id])
    @fornecedor_custo.destroy

    respond_to do |format|
      format.html { redirect_to fornecedor_custos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fornecedor_custos_helper.rb
module FornecedorCustosHelper
end

app/views/fornecedor_custos/_form.html.erb
<%= form_for(@fornecedor_custo) do |f| %>
  <% if @fornecedor_custo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fornecedor_custo.errors.count, "error") %> prohibited this fornecedor_custo from being saved:</h2>

      <ul>
      <% @fornecedor_custo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :produto_id %><br />
    <%= f.collection_select :produto_id, Produto.all, :id, :nome %>
  </div>
  <div class="field">
    <%= f.label :preco %><br />
    <%= f.text_field :preco %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :obs %><br />
    <%= f.text_area :obs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fornecedor_custos/edit.html.erb
<h1>Editing fornecedor_custo</h1>

<%= render 'form' %>

<%= link_to 'Show', @fornecedor_custo %> |
<%= link_to 'Back', fornecedor_custos_path %>

app/views/fornecedor_custos/index.html.erb
<h1>Listing fornecedor_custos</h1>

<table>
  <tr>
    <th>Produto</th>
    <th>Preco</th>
    <th>Data</th>
    <th>Obs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fornecedor_custos.each do |fornecedor_custo| %>
  <tr>
    <td><%= fornecedor_custo.produto_id %></td>
    <td><%= fornecedor_custo.preco %></td>
    <td><%= fornecedor_custo.data %></td>
    <td><%= fornecedor_custo.obs %></td>
    <td><%= link_to 'Show', fornecedor_custo %></td>
    <td><%= link_to 'Edit', edit_fornecedor_custo_path(fornecedor_custo) %></td>
    <td><%= link_to 'Destroy', fornecedor_custo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fornecedor custo', new_fornecedor_custo_path %>

app/views/fornecedor_custos/new.html.erb
<h1>New fornecedor_custo</h1>

<%= render 'form' %>

<%= link_to 'Back', fornecedor_custos_path %>

app/views/fornecedor_custos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Produto:</b>
  <%= @fornecedor_custo.produto_id %>
</p>

<p>
  <b>Preco:</b>
  <%= @fornecedor_custo.preco %>
</p>

<p>
  <b>Data:</b>
  <%= @fornecedor_custo.data %>
</p>

<p>
  <b>Obs:</b>
  <%= @fornecedor_custo.obs %>
</p>


<%= link_to 'Edit', edit_fornecedor_custo_path(@fornecedor_custo) %> |
<%= link_to 'Back', fornecedor_custos_path %>