config/routes.rb
Sistema::Application.routes.draw do
  devise_for :users

  resources :fornecedor_custos, :path => "custos"

  resources :fornecedors, :path => 'fornecedores'

  resources :marcas

  resources :relatorios
  resources :produtos

  root :to => 'welcome#index'

end

app/models/marca.rb
class Marca < ActiveRecord::Base
  attr_accessible :descricao, :nome, :fornecedor_id
  has_many :produtos
  belongs_to :fornecedor
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @marcas }
    end
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
    @marca = Marca.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @marca }
    end
  end

  # GET /marcas/new
  # GET /marcas/new.json
  def new
    @marca = Marca.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @marca }
    end
  end

  # GET /marcas/1/edit
  def edit
    @marca = Marca.find(params[:id])
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(params[:marca])

    respond_to do |format|
      if @marca.save
        format.html { redirect_to @marca, notice: 'Marca was successfully created.' }
        format.json { render json: @marca, status: :created, location: @marca }
      else
        format.html { render action: "new" }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /marcas/1
  # PUT /marcas/1.json
  def update
    @marca = Marca.find(params[:id])

    respond_to do |format|
      if @marca.update_attributes(params[:marca])
        format.html { redirect_to @marca, notice: 'Marca was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    @marca = Marca.find(params[:id])
    @marca.destroy

    respond_to do |format|
      format.html { redirect_to marcas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/views/marcas/_form.html.erb
<%= form_for(@marca) do |f| %>
  <% if @marca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
      <% @marca.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
 

 <%= f.collection_select :fornecedor_id, Fornecedor.all, :id, :nome %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marcas/edit.html.erb
<h1>Editing marca</h1>

<%= render 'form' %>

<%= link_to 'Show', @marca %> |
<%= link_to 'Back', marcas_path %>

app/views/marcas/index.html.erb
<h1>Listing marcas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Fornecedor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @marcas.each do |marca| %>
  <tr>
    <td><%= marca.nome %></td>
    <td><%= marca.descricao %></td>
    <td></td>
    <td><%= link_to 'Show', marca %></td>
    <td><%= link_to 'Edit', edit_marca_path(marca) %></td>
    <td><%= link_to 'Destroy', marca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Marca', new_marca_path %>

app/views/marcas/new.html.erb
<h1>New marca</h1>

<%= render 'form' %>

<%= link_to 'Back', marcas_path %>

app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @marca.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @marca.descricao %>
</p>

<p>
  <b>Fornecedor:</b>
  <%= @marca.fornecedor.first.nome %>
</p>


<%= link_to 'Edit', edit_marca_path(@marca) %> |
<%= link_to 'Back', marcas_path %>